

#  ______  __    __  .______    _______  _______    ___      .______   .___  ___.
# /      ||  |  |  | |   _  \  |   ____||   ____|  /   \     |   _  \  |   \/   |
#|  ,----'|  |  |  | |  |_)  | |  |__   |  |__    /  ^  \    |  |_)  | |  \  /  |
#|  |     |  |  |  | |   _  <  |   __|  |   __|  /  /_\  \   |      /  |  |\/|  |
#|  `----.|  `--'  | |  |_)  | |  |____ |  |    /  _____  \  |  |\  \  |  |  |  |
# \______| \______/  |______/  |_______||__|   /__/     \__\ | _| `._| |__|  |__|
#

# Name of the Farm world
world: farms

#Current Amount of farms that been generated
farmamount: 0

#List of all farms
farms: []

#List of all players
players: []

#List of all the Schematic
schematics:
  trees:
  - '0'
  - '1'
  grass:
  - '0'