name: CubeFarm
version: 1.0
author: Candy
api-version: 1.13
main: me.candyyn.cubefarm.CubeFarm
commands:
        farm:
           description: Brings up the basic help window for your Farm
           usage: /farm
        balance:
           description: Brings up the basic help window for your balace
           usage: /balance